### ISSUE TITLE
异仓库部署方式

### ISSUE THREAD

**Issue by hailaz** [hailaz/gfdoc-md#3]
可以使用personal_token的方式https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-deploy-to-external-repository-external_repository

在https://github.com/settings/tokens?type=beta新增token，指定仓库，给予contents的读写权限。
![0544b240e46123064f315c8dcf3d67f](https://github.com/hailaz/gfdoc-md/assets/29968474/7d82955a-0da3-49a8-a30d-bcdff1de6922)

```
      - name: Deploy to GitHub Pages gfqa
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: hailaz/gf
          # 要发布到 `gh-pages` 分支的构建输出：
          publish_dir: ./build
          # 下面两行会将此次部署 commit 的作者设置为官方的
          # GH-Actions 机器人：
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # 如果不设置这两个字段，GH actions 机器人会被默认使用。
          # 你可以用自己的用户信息替换它们。
```
